package com.epam.edai.run8.team11.model.dish;

import com.epam.edai.run8.team11.model.dish.dishstate.DishState;
import com.epam.edai.run8.team11.model.dish.dishstate.DishStateConverter;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@DynamoDbBean
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Dish {

    public static final String DISH_ID = "dishId";
    public static final String LOCATION_ID = "locationId";

    @JsonProperty("id")
    private String dishId;
    private String locationId;
    private String calories;
    private String carbohydrates;
    private String description;
    private String fats;
    private String imageUrl;
    private Boolean isPopular;
    private Boolean isSpeciality;
    private String name;
    private Double price;
    private String proteins;
    private DishState state;
    private String vitamins;
    private Double weight;

    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getDishId() {
        return dishId;
    }

    @DynamoDbSortKey
    public String getLocationId() {
        return locationId;
    }

    @DynamoDbConvertedBy(DishStateConverter.class)
    public DishState getState() {
        return state;
    }
}