package com.epam.edai.run8.team11.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.util.List;
import java.util.Objects;

@DynamoDbBean
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Location {

    public static final String LOCATION_ID = "locationId";

    // Partition key with UUID generation
    @JsonProperty("id")
    private String locationId;
    private String address;
    private Integer averageOccupancy;
    private String description;
    private List<String> dishIds;
    private String imageUrl;
    private String name;
    private Double rating;
    private Integer totalCapacity;

    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getLocationId() {
        return locationId;
    }

}

