package com.epam.edai.run8.team11.model.reservation;

import com.epam.edai.run8.team11.model.reservation.clienttype.ClientType;
import com.epam.edai.run8.team11.model.reservation.clienttype.ClientTypeConverter;
import com.epam.edai.run8.team11.model.reservation.reservationstatus.ReservationStatus;
import com.epam.edai.run8.team11.model.reservation.reservationstatus.ReservationStatusConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

@DynamoDbBean
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Reservation {

    private String id;
    private Boolean bookedByWaiter;
    private ClientType clientType;
    private String customerName;
    private String customerId;
    private String date;
    private String feedbackId;
    private String guestsNumber;
    private String locationAddress;
    private String locationId;
    private String preOrder;
    private ReservationStatus status;
    private Integer tableNumber;
    private String timeSlot;
    private String waiterId;
    private String waiterName;

    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getId() {
        return id;
    }

    @DynamoDbConvertedBy(ClientTypeConverter.class)
    public ClientType getClientType() {
        return clientType;
    }

    @DynamoDbConvertedBy(ReservationStatusConverter.class)
    public ReservationStatus getStatus() {
        return status;
    }
}