package com.epam.edai.run8.team11.model.feedback;

import com.epam.edai.run8.team11.model.feedback.feedbacktype.FeedbackType;
import com.epam.edai.run8.team11.model.feedback.feedbacktype.FeedbackTypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.LocalDate;

@DynamoDbBean
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Feedback {

    public static String FEEDBACK_ID = "feedbackId";
    public static String LOCATION_ID = "locationId";
    public static String TYPE = "type";

    private String feedbackId;
    private LocalDate date;
    private String locationId;
    private Double rating;
    private String review;
    private FeedbackType type;
    private String userAvatarUrl;
    private String userEmail;

    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getFeedbackId() {
        return feedbackId;
    }

    @DynamoDbConvertedBy(FeedbackTypeConverter.class)
    public FeedbackType getType() {
        return type;
    }
}
